language: c
dist: xenial

addons:
        apt:
                packages:
                        - libelf-dev
                        - bc
                        - bison
                        - flex
                        - codespell
                        - ocaml
                        - automake
                        - autoconf

matrix:
        include:
                env: KERNEL_VERSION=5.1.5

cache:
        directories:
                - $HOME/bin
                - $HOME/lib
                - $HOME/.opam

# Later
before_install:
        - sudo apt-get update
        - sudo apt-get install linux-headers-$(uname -r)
        - sparse --version || ( git clone git://git.kernel.org/pub/scm/devel/sparse/sparse.git && cd sparse && make HAVE_LLVM='no' install && cd - )
        - spatch --version || ( wget --quiet https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s $HOME/bin 4.05.0 && eval $(opam config env) && opam install -y pcre.7.1.1 menhir && wget --quiet https://github.com/coccinelle/coccinelle/archive/1.0.7.tar.gz && tar xf 1.0.7.tar.gz && cd coccinelle-1.0.7 && ./autogen && ./configure --prefix=$HOME --without-bash-completion && make install && cd - )

before_script:
        - export KMDIR="$(pwd)"
        - cd ..
        # kernel configuration for static analysys && checkpatch
        - wget --quiet https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-$KERNEL_VERSION.tar.xz
        - tar xf linux-$KERNEL_VERSION.tar.xz
        - export CHECK_KERNEL="$(pwd)/linux-$KERNEL_VERSION"
        - cd $CHECK_KERNEL
        - make defconfig
        - make modules_prepare

script:
        - cd $KMDIR
        - make KERNELDIR=$CHECK_KERNEL style
        - make KERNELDIR=$CHECK_KERNEL check
        - ( eval $(opam config env) && make KERNELDIR=$CHECK_KERNEL coccicheck ) || ( cd $CHECK_KERNEL && cat cocci.debug && exit 1 )
        - make load
#        - make test
